name: lint-check

on: [pull_request]

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get list of changed files
        id: changed-files
        uses: actions/github-script@v7
        with:
          script: |
            const getAllChangedFiles = async (github, context) => {
              let changedFiles = [];
              let page = 1;
              while (true) {
                const { data: files } = await github.rest.pulls.listFiles({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  per_page: 100,
                  page: page,
                });
                if (files.length === 0) {
                  break;
                }
                changedFiles = changedFiles.concat(files.map(f => f.filename));
                page++;
              }
              return changedFiles;
            };

            const changedFiles = await getAllChangedFiles(github, context).then(files => {
              return files.filter(f => /\.(js|jsx|ts|tsx|json|css|md)$/.test(f))
            })

            if (changedFiles.length === 0) {
              core.setOutput('skip', 'true');
            } else {
              core.setOutput('skip', 'false');
              core.setOutput('changedFiles', changedFiles.join(' '));
            }

      - name: Set up Node.js
        if: steps.changed-files.outputs.skip == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        if: steps.changed-files.outputs.skip == 'false'
        run: npm ci

      - name: Run Prettier check on changed files
        id: prettier-check
        if: steps.changed-files.outputs.skip == 'false'
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.changedFiles }}"
          echo "Running Prettier on changed files:"
          echo "$CHANGED_FILES"
          output=$(npx prettier --check $CHANGED_FILES || true)
          echo "$output"
          echo "$output" > prettier_output.txt
          if echo "$output" | grep -q "Run Prettier to fix"; then
            exit 1
          fi
        continue-on-error: true

      - name: Set Prettier output to environment variable
        if: steps.changed-files.outputs.skip == 'false'
        run: |
          echo "PRETTIER_OUTPUT=$(cat prettier_output.txt)" >> $GITHUB_ENV

      - name: Post or update Prettier results
        if: steps.changed-files.outputs.skip == 'false'
        uses: actions/github-script@v7
        env:
          PRETTIER_OUTCOME: ${{ steps.prettier-check.outcome }}
          PRETTIER_OUTPUT: ${{ env.PRETTIER_OUTPUT }}
        with:
          script: |
            const commentIdentifier = '<!-- prettier-check-comment -->';
            let body;

            if (process.env.PRETTIER_OUTCOME === 'success') {
              body = `${commentIdentifier}\n**Prettier check passed!** 🎉`;
            } else {
              body = `${commentIdentifier}\n**Prettier check failed for the following files:**\n\n\`\`\`\n${process.env.PRETTIER_OUTPUT}\n\`\`\``;
            }

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const comment = comments.find(comment => comment.body.includes(commentIdentifier));

            if (comment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body: body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body,
              });
            }

      - name: Run Next Lint
        if: steps.changed-files.outputs.skip == 'false'
        run: |
          npx next lint --quiet
