name: lint-check

on: [pull_request]

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prettier Bot
        uses: noyobo/prettier-bot@v1
