name: lint-check

on: [pull_request]

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get list of changed files
        id: changed-files
        uses: actions/github-script@v7
        with:
          script: |
            const getAllChangedFiles = async (github, context) => {
              let changedFiles = [];
              let page = 1;
              while (true) {
                const { data: files } = await github.rest.pulls.listFiles({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  per_page: 100,
                  page: page,
                });
                if (files.length === 0) {
                  break;
                }
                changedFiles = changedFiles.concat(files.map(f => f.filename));
                page++;
              }
              return changedFiles;
            };

            const changedFiles = await getAllChangedFiles(github, context).then(files => {
              return files.filter(f => /\.(js|jsx|ts|tsx|json|css|md)$/.test(f))
            })

            if (changedFiles.length === 0) {
              core.setOutput('skip', 'true');
            } else {
              core.setOutput('skip', 'false');
              core.setOutput('changedFiles', changedFiles.join(' '));
            }

      - name: Pass Prettier check
        if: steps.changed-files.outputs.skip == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const commentIdentifier = '<!-- prettier-check-comment -->';
            const body = `${commentIdentifier}\n**💄Prettier check passed!** 🎉`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const comment = comments.find(comment => comment.body.includes(commentIdentifier));

            if (comment) {
              await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id,
                  body: body,
              });
            } else {
              await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: body,
              });
            }

      - name: Set up Node.js
        if: steps.changed-files.outputs.skip == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        if: steps.changed-files.outputs.skip == 'false'
        run: npm ci

      - name: Run Prettier check on changed files
        id: prettier-check
        if: steps.changed-files.outputs.skip == 'false'
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.changedFiles }}"
          echo "Running Prettier on changed files:"
          echo "$CHANGED_FILES"
          npx prettier --check 'app/page.tsx' > prettier_output.txt 2>&1 || true
          output=$(cat prettier_output.txt)
          echo "$output"
          if echo "$output" | grep -q "Run Prettier to fix"; then
            echo "Prettier check failed."
            exit 1
          else
            echo "Prettier check passed."
          fi
        continue-on-error: true

      - name: Post or update Prettier results
        if: steps.changed-files.outputs.skip == 'false'
        uses: actions/github-script@v7
        env:
          PRETTIER_OUTCOME: ${{ steps.prettier-check.outcome }}
        with:
          script: |
            const fs = require('fs');
            const commentIdentifier = '<!-- prettier-check-comment -->';

            let body;

            if (process.env.PRETTIER_OUTCOME === 'success') {
              body = `${commentIdentifier}\n**💄Prettier check passed!** 🎉`;
            } else {
              const PRETTIER_OUTPUT = fs.readFileSync('prettier_output.txt', 'utf8');
              const lines = PRETTIER_OUTPUT.trim().split('\n')
              lines.shift();
              lines.pop();
              const prettierCommand = `npx prettier --write ${lines.map(line => line.trim().replace('[warn] ', '')).join(' ')}`;
              body = `${commentIdentifier}\n**🚨Prettier check failed for the following files:**\n\n\`\`\`\n${PRETTIER_OUTPUT.trim()}\n\`\`\`\n\nTo fix the issue, run the following command:\n\n\`\`\`\n${prettierCommand}\n\`\`\``;
            }

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const comment = comments.find(comment => comment.body.includes(commentIdentifier));

            if (comment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body: body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body,
              });
            }

            if (process.env.PRETTIER_OUTCOME !== 'success') {
              process.exit(1);
            }

      - name: Run Next Lint
        if: steps.changed-files.outputs.skip == 'false'
        run: |
          npx next lint --quiet
